//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Xcode Templates
//

import UIKit

// add function which doesn't have return types
protocol ___VARIABLE_sceneName____HandleUIEvents: ___VARIABLE_sceneName____HandleCellUIEvents {
    func doSomething()
}

// add function which doesn't have return types
protocol ___VARIABLE_sceneName____DisplayUI: class {
    func toggle(_ isLoading: Bool)
}

// add function which doesn't have return types
protocol ___VARIABLE_sceneName____HandleCellUIEvents: class {
    func setValue(_ value: String?, inputType: ___VARIABLE_sceneName___.InputType)
}
