//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Zco Xcode Templates
//

import UIKit

protocol ___VARIABLE_sceneName____HandleUIEvents: ___VARIABLE_sceneName____HandleCellUIEvents {
    func doSomething()
}

protocol ___VARIABLE_sceneName____DisplayUI: class {
    func toggle(_ isLoading: Bool)
}

protocol ___VARIABLE_sceneName____HandleCellUIEvents: class {
    func getValueFor(_ inputType: ___VARIABLE_sceneName___.InputType) -> String?
    func setValue(_ value: String?, inputType: ___VARIABLE_sceneName___.InputType)
}
