//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Zco Xcode Templates
//
enum ___VARIABLE_sceneName___ {
    struct Request: JSONDictionaryDeserializable {
        func toJSON() -> [String: Any] {
            return []
        }
    }
    struct Response: JSONDictionarySerializable {
        init(json: [String: Any]) throws {
        }
    }
}
