//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the ZCo Swift Xcode Templates
//

import UIKit


class ___VARIABLE_sceneName___ViewController: BaseViewController {
    
    var eventHandler: ___VARIABLE_sceneName____HandleUIEvents!
    weak var viewModel: ___VARIABLE_sceneName___ViewModel!
    @IBOutlet weak var sbControl: ___VARIABLE_sceneName___SBControl!
    private var uiController: ___VARIABLE_sceneName___UIController!
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        sbControl.addCustomizations()
        uiController = ___VARIABLE_sceneName___UIController(sbControl.tableView, eventHandler: eventHandler)
    }
    deinit {
        printDebug("\(String(describing: self)) is being deInitialized.\n")
    }
}

extension ___VARIABLE_sceneName___ViewController: ___VARIABLE_sceneName____DisplayUI {
    func toggle(_ isLoading: Bool) {
    }
}
