//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the ZCo Swift Xcode Templates
//

import UIKit
class ___VARIABLE_cellName___TableViewCell: UITableViewCell {
    //@IBOutlet weak var roomLabel: UILabel!
    @IBOutlet var inputTextField: UITextField!
    override func awakeFromNib() {
        super.awakeFromNib()
        //Set font and color here
        //roomLabel.font = UIFont.regular(10)
//        let tapGestureStarted = UITapGestureRecognizer(target: self, action: #selector(didTapCell(_:)))
//        tapGestureStarted.numberOfTapsRequired = 1
//        self.contentView.addGestureRecognizer(tapGestureStarted)
    }
    var cellController: ___VARIABLE_sceneName___.InputField? {
        didSet {
            guard let cellViewModel = cellController else { return }
            inputTextField.tag = cellViewModel.inputType.rawValue
        }
    }
    func setTextValue(_ value: String?) {
        inputTextField.text = value
    }
//    @objc func didTapCell(_ gestureRecognizer: UITapGestureRecognizer) {
//        let view = gestureRecognizer.view
//        let loc = gestureRecognizer.location(in: view)
//        inputTextField.becomeFirstResponder()
//    }
}

