//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Swift Xcode Templates
//

import UIKit
class ___VARIABLE_cellName___TableViewCell: UITableViewCell {
    //@IBOutlet weak var roomLabel: UILabel!
    override func awakeFromNib() {
        super.awakeFromNib()
        //Set font and color here
        //roomLabel.font = UIFont.regular(10)
    }
    var cellController: ___VARIABLE_cellName___CellPresentable? {
        didSet {
            guard let cellViewModel = cellController else { return }
        }
    }
}

