//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Swift Xcode Templates
//

import UIKit
class ___VARIABLE_sceneName___UIController {
    
    //weak var eventHandler: ___VARIABLE_sceneName____HandleCellUIEvents!
    fileprivate let collectionViewDataSource: CollectionViewDataSource<___VARIABLE_cellName___CellPresentable, ___VARIABLE_cellName___CollectionViewCell>
    
    init(_ collectionView: UICollectionView, eventHandler: ___VARIABLE_sceneName____HandleCellUIEvents) {
        //self.eventHandler = eventHandler
        self.collectionViewDataSource = CollectionViewDataSource<___VARIABLE_cellName___CellPresentable, ___VARIABLE_cellName___CollectionViewCell>(collectionView: collectionView)
        collectionView.delegate = collectionViewDataSource
        collectionView.dataSource = collectionViewDataSource
        collectionViewDataSource.actionHandler = { [weak self] (model, indexPath) in
            guard let strongSelf = self else { return }
            //strongSelf.eventHandler.handleRoomSelection(model: model, cellIndex: indexPath.item)
        }
    }
    
    func loadBitReelRooms(_ rooms: [___VARIABLE_cellName___ViewModel]) {
        collectionViewDataSource.cellSizeDelegate = self
        collectionViewDataSource.dataSource = rooms
    }
    
    deinit {
        printDebug("\(String(describing: self)) is being deInitialized.")
    }
}
