//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the ZCo Swift Xcode Templates
//

import UIKit

protocol ___VARIABLE_sceneName___ViewModel: class {
    func doSomeWork()
}

class Default___VARIABLE_sceneName___ViewModel: ___VARIABLE_sceneName___ViewModel {
    init() {
        
    }
    func doSomeWork() {
    }
}
