//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Swift Xcode Templates
//

protocol ___VARIABLE_sceneName___ViewModel: class {
    func getValueFor(_ inputType: ___VARIABLE_sceneName___.InputType) -> String?
}

class Default___VARIABLE_sceneName___ViewModel {
    
    init() {
        
    }
    
    func setValue(_ value: String?, inputType: ___VARIABLE_sceneName___.InputType) {
        
    }
}

//MARK: ___VARIABLE_sceneName___ViewModel
extension Default___VARIABLE_sceneName___ViewModel: ___VARIABLE_sceneName___ViewModel {
    
    func getValueFor(_ inputType: ___VARIABLE_sceneName___.InputType) -> String? {
        return nil
    }
}
