//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Swift Xcode Templates
//

import UIKit
protocol ___VARIABLE_cellName___CellPresentable {
    var roomName: String? { get }
}
class ___VARIABLE_cellName___ViewModel: ___VARIABLE_cellName___CellPresentable {
    var roomName: String?
}


