//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Xcode Templates
//
protocol ___VARIABLE_sceneName___Service {
    func cancelWebServiceCalls()
}

class ___VARIABLE_sceneName___API {
    var connection: NetworkingAPI
    init(_ connection: NetworkingAPI) {
        self.connection = connection
    }

}

extension ___VARIABLE_sceneName___API: ___VARIABLE_sceneName___Service {
    func cancelWebServiceCalls() {
        self.connection.cancelServiceCall()
    }
}
