//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Swift Xcode Templates
//

import CoreData

protocol DataMappable {
    func mapPropertiesTo<T: NSManagedObject>(_ managedObj: T.Type)
    static func initByMapProertiesFrom<T: NSManagedObject>(_ managedObj: T.Type) -> Self
}

class ___VARIABLE_sceneName___DataStore {
    
    deinit {
        printDebug("\(String(describing: self)) is being deInitialized.\n")
    }
}

