//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the ZCo Swift Xcode Templates
//

import UIKit

protocol ___VARIABLE_cellName___CellPresentable: class {
    
}

class ___VARIABLE_cellName___ViewModel: ___VARIABLE_cellName___CellPresentable {
    init() {
        
    }
}
