//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Xcode Templates
//

import UIKit

// add functions which can invoke from view controllers. No return types
protocol ___VARIABLE_sceneName____HandleUIEvents: class {
    func doSomething()
}

// add functions which can invoke form Presenter. No return types
protocol ___VARIABLE_sceneName____DisplayUI: class {
    func toggle(_ isLoading: Bool)
}
