//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Zco Xcode Templates
//


class ___VARIABLE_sceneName___Presenter {
    var router: ___VARIABLE_sceneName___Router!
    var viewModel: Default___VARIABLE_sceneName___ViewModel
    weak var displayUI: ___VARIABLE_sceneName____DisplayUI!
    init(_ viewModel: Default___VARIABLE_sceneName___ViewModel) {
        self.viewModel = viewModel
    }
}
extension ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName____HandleUIEvents {
    func doSomething() {
        
    }
}
