//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Xcode Templates
//
enum ___VARIABLE_sceneName___ {
    
    struct Request: Encodable {
    }
    
    struct Response: Decodable {
    }
    
}
