//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Xcode Templates
//


protocol ___VARIABLE_sceneName___Service {
    //func login(request: LoginRequest, completion: (PatientProfile?, MOError?))
}

class ___VARIABLE_sceneName___API: ___VARIABLE_sceneName___Service {
    
    var connection: NetworkingAPI
    
    init(_ connection: NetworkingAPI) {
        self.connection = connection
    }
//    func login(request: LoginRequest, completion: (PatientProfile?, MOError?)) {
//        let data = RequestData(endpoint: .login, parameters: nil, body: request.toJSON())
//        connection.makeWebserviceCall(method: .post, with: data) { [weak self] (response: Result<LoginResponse>) in
//            switch response {
//            case .success(let response):
//                UserManager.sharedInstance.patientProfile = response.patient
//                completion(profile, err)
//            case .failure(let err):
//                completion(nil, err)
//            }
//        }
//    }
}
