//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Swift MVP+VM Swift Xcode Templates
//

import UIKit

//declare getters and functions with return variables which can access from view controller
protocol ___VARIABLE_sceneName___ViewModel: class {
    var titleText: String {get}
    //var reloadUserProfile: ((UpdatedProfileStatus) -> Void)? {get set}
}

class Default___VARIABLE_sceneName___ViewModel {
    
    var reloadUserProfile: ((UpdatedProfileStatus) -> Void)?
    init() {
        
    }

}

//MARK: ___VARIABLE_sceneName___ViewModel
extension Default___VARIABLE_sceneName___ViewModel: ___VARIABLE_sceneName___ViewModel {
    
    var titleText: String {
        return "My ViewController"
    }
}
